-- ============================================================
-- Performance indexes.
-- harvests (V20) and notifications (V23) shipped with no indexes
-- although they are hit by nearly every analytics/report/history
-- query; several foreign keys were never indexed (Postgres does
-- not index FKs automatically).
-- ============================================================

-- ---------- harvests ----------
CREATE INDEX idx_harvest_cycle
    ON harvests (pond_cycle_id);

CREATE INDEX idx_harvest_date
    ON harvests (harvest_date);

CREATE INDEX idx_harvest_status
    ON harvests (status);

CREATE INDEX idx_harvest_uploaded_by
    ON harvests (uploaded_by);

CREATE INDEX idx_harvest_cancelled_by
    ON harvests (cancelled_by);

-- Covers the hot analytics pattern:
-- WHERE pond_cycle_id = ? AND status = ? [AND harvest_date BETWEEN ...]
CREATE INDEX idx_harvest_cycle_status_date
    ON harvests (pond_cycle_id, status, harvest_date);

-- ---------- notifications ----------
CREATE INDEX idx_notifications_status
    ON notifications (status);

CREATE INDEX idx_notifications_site_status
    ON notifications (site_id, status);

CREATE INDEX idx_notifications_created_at
    ON notifications (created_at DESC);

-- ---------- previously unindexed foreign keys ----------
CREATE INDEX idx_users_role
    ON users (role_id);

CREATE INDEX idx_medicine_created_by
    ON medicine_entries (created_by);

CREATE INDEX idx_medicine_cancelled_by
    ON medicine_entries (cancelled_by);

CREATE INDEX idx_medicine_restored_by
    ON medicine_entries (restored_by);

CREATE INDEX idx_medicine_photo_uploaded_by
    ON medicine_photos (uploaded_by);

CREATE INDEX idx_feed_delivery_delivered_by
    ON feed_deliveries (delivered_by);

CREATE INDEX idx_feed_delivery_cancelled_by
    ON feed_deliveries (cancelled_by);

CREATE INDEX idx_feed_delivery_restored_by
    ON feed_deliveries (restored_by);

CREATE INDEX idx_feed_entry_cancelled_by
    ON feed_entries (cancelled_by);

CREATE INDEX idx_feed_entry_restored_by
    ON feed_entries (restored_by);

CREATE INDEX idx_site_delivery_cancelled_by
    ON site_deliveries (cancelled_by);

CREATE INDEX idx_site_delivery_restored_by
    ON site_deliveries (restored_by);

CREATE INDEX idx_receipt_uploaded_by
    ON site_delivery_receipts (uploaded_by);

CREATE INDEX idx_receipt_cancelled_by
    ON site_delivery_receipts (cancelled_by);

CREATE INDEX idx_receipt_restored_by
    ON site_delivery_receipts (restored_by);

-- Covers dashboard/analytics aggregates:
-- WHERE pond_cycle_id = ? AND feed_date = / BETWEEN ? AND status = ?
CREATE INDEX idx_feed_entry_cycle_date_status
    ON feed_entries (pond_cycle_id, feed_date, status);

-- ---------- cleanup ----------
-- site_id already carries a UNIQUE constraint (implicit index);
-- the explicit index duplicated it.
DROP INDEX IF EXISTS idx_feed_inventory_site;

-- ---------- trigram indexes for global search ----------
-- Search uses leading-wildcard LIKE (%kw%), which B-tree indexes
-- cannot serve; pg_trgm GIN indexes on LOWER(col) match the
-- LOWER(col) LIKE LOWER('%kw%') pattern generated by JPQL.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_ponds_code_trgm
    ON ponds USING gin (LOWER(pond_code) gin_trgm_ops);

CREATE INDEX idx_ponds_name_trgm
    ON ponds USING gin (LOWER(pond_name) gin_trgm_ops);

CREATE INDEX idx_sites_code_trgm
    ON sites USING gin (LOWER(site_code) gin_trgm_ops);

CREATE INDEX idx_sites_name_trgm
    ON sites USING gin (LOWER(site_name) gin_trgm_ops);

CREATE INDEX idx_harvests_buyer_trgm
    ON harvests USING gin (LOWER(buyer_name) gin_trgm_ops);

CREATE INDEX idx_notifications_title_trgm
    ON notifications USING gin (LOWER(title) gin_trgm_ops);
